# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        "eBot :: Your match manager for CS:GO"
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [bootstrap.min.css, tipsy.css, datetimepicker.css, datepicker.css, flags.css, datatable.bootstrap.css, pnotify.custom.min.css]

  javascripts:    [jquery-1.8.2.min.js, bootstrap.min.js, bootstrap-filestyle.min.js,  jquery.validate.min.js, bootbox.js, jquery.tipsy.js, jquery.tablesorter.min.js, jquery.datatable.min.js, jquery.autosize.min.js, datatable.bootstrap.js, heatmap.js, raphael-min.js, aes.js, bootstrap-datetimepicker.min.js, bootstrap-datepicker.js,pnotify.custom.min.js]

  has_layout:     true
  layout:         layout