# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        eBot Administration
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [bootstrap.min.css, tipsy.css]

  javascripts:    [jquery-1.8.2.min.js, bootstrap.min.js, jquery.validate.min.js, jquery.tipsy.js, jquery.tablesorter.min.js, heatmap.js ]

  has_layout:     true
  layout:         layout
