# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  <?php require_once(sfConfig::get('sf_root_dir')."/config/app_user.yml") ?>

  .array:
    maps: [ de_dust2, de_nuke, de_inferno, de_train, de_mirage, de_vertigo, de_cache, de_overpass, de_cbble,]
    flag_team:
      ZA:	AFRIQUE DU SUD
      DZ:	ALGERIE
      DE:	ALLEMAGNE
      SA:	ARABIE SAOUDITE
      AR:	ARGENTINE
      AU:	AUSTRALIE
      AT:	AUTRICHE
      BY:	BELARUS
      BE:	BELGIQUE
      BR:	BRESIL
      BG:	BULGARIE
      CA:	CANADA
      CL:	CHILIE
      CN:	CHINE
      CC:	CIS
      KR:	COREE DU SUD
      HR:	CROATIE
      DK:	DANEMARK
      AE:	EMIRATS ARABES UNIS
      ES:	ESPAGNE
      EE:	ESTONIA
      US:	ETATS-UNIS
      EU:   EUROPE
      FI:	FINLAND
      FR:	FRANCE
      GR:	GRECE
      HU:	HONGRIE
      IN:	INDE
      ID:	INDONESIE
      IR:	IRAN
      IE:	IRELANDE
      IS:	ISLANDE
      IL:	ISRAEL
      IT:	ITALIE
      JP:	JAPON
      KZ:	KAZAKHSTAN
      LV:	LETTONIE
      LY:	LIBYE
      LT:	LITUANIE
      LU:	LUXEMBOURG
      MY:	MALAISIE
      MX:	MEXIQUE
      NO:	NORVEGE
      NZ:	NOUVELLE-ZELANDE
      PK:	PAKISTAN
      NL:	PAYS-BAS
      PE:	PEROU
      PH:	PHILIPPINES
      PL:	POLOGNE
      PT:	PORTUGAL
      CZ:	REPUBLIQUE TCHEQUE
      RO:	ROUMANIE
      GB:	ROYAUME-UNI
      RU:	RUSSIE
      RS:	SERBIE
      SG:	SINGAPOUR
      SK:	SLOVAQUIE
      SI:	SLOVENIE
      SE:	SUEDE
      CH:	SUISSE
      TW:	TAIWAN
      TH:	THAILANDE
      TR:	TURQUIE
      UA:	UKRAINE
      VE:	VENEZUELA

    flag_team_en:
      DZ:	ALGERIA
      AR:	ARGENTINA
      AU:	AUSTRALIA
      AT:	AUSTRIA
      BY:	BELARUS
      BE:	BELGIUM
      BR:	BRAZIL
      BG:	BULGARIA
      CA:	CANADA
      CL:	CHILE
      CN:	CHINA
      CC:	CIS
      HR:	CROATIA
      CZ:	CZECH REPUBLIC
      DK:	DENMARK
      EE:	ESTONIA
      EU:   EUROPE
      FI:	FINLAND
      FR:	FRANCE
      DE:	GERMANY
      GR:	GREECE
      HU:	HUNGARY
      IS:	ICELAND
      IN:	INDIA
      ID:	INDONESIA
      IR:	IRAN
      IE:	IRELAND
      IL:	ISRAEL
      IT:	ITALY
      JP:	JAPAN
      KZ:	KAZAKHSTAN
      KR:	KOREA
      LV:	LATVIA
      LY:	LIBYA
      LT:	LITHUANIA
      LU:	LUXEMBOURG
      MK:       MACEDONIA
      MY:	MALAYSIA
      MX:	MEXICO
      NL:	NETHERLANDS
      NZ:	NEW ZEALAND
      NO:	NORWAY
      PK:	PAKISTAN
      PE:	PERU
      PH:	PHILIPPINES
      PL:	POLAND
      PT:	PORTUGAL
      RO:	ROMANIA
      RU:	RUSSIAN FEDERATION
      SA:	SAUDI ARABIA
      RS:	SERBIA
      SG:	SINGAPORE
      SK:	SLOVAKIA
      SI:	SLOVENIA
      ZA:	SOUTH AFRICA
      ES:	SPAIN
      SE:	SWEDEN
      CH:	SWITZERLAND
      TW:	TAIWAN
      TH:	THAILAND
      TR:	TURKEY
      UA:	UKRAINE
      AE:	UNITED ARAB EMIRATES
      GB:	UNITED KINGDOM
      US:	UNITED STATES
      VE:	VENEZUELA
      TN:	TUNISIA
      MA:	Morocco
      HK:	Hong Kong
      VN:	VIETNAM
      MN:	MONGOLIA
  version: "3.2.0 threads"
